# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.12.0
title: dsda-doom
description: A modern but conservative Doom source port
baseurl: "/dsda-doom"
url: "https://dsda-org.github.io"
repository: dsda-org/dsda-doom

permalink: pretty

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/prboom2/ICONS/dsda-doom.png"

# Enable or disable the site search
search_enabled: true
search:
  # Enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "dsda-doom on GitHub":
    - "https://github.com/dsda-org/dsda-doom"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:
  - title: dsda-doom on GitHub
    url: https://github.com/dsda-org/dsda-doom

# Show navigation error report
nav_error_report: true # default is false/nil.

liquid:
  error_mode: strict
  strict_filters: true

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

# When commented out, callouts_level defaults to quiet for the light scheme, and loud for dark
# callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607


exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/
  - spec/
  - tmp
  - .rspec
  # repo specific
  - prboom2/src/
